### basic settings

# site properties and page defaults
title: maser lab
description: Website for Dr Jonathan (Jon) Breeze's lab at UCL, researching room-temperature solid-state masers, quantum technology and condensed matter physics.
logo: images/ucl-logo.svg
header: images/maser1.jpg
footer: images/maser1.jpg
baseurl: ''
url: 'https://breezelab.org'

# site social media and other links
links:
  email: j.breeze@ucl.ac.uk
  google-scholar: Jonathan Breeze
  github: breeze-lab
  twitter: jonbreeze
  linkedin: jonathan-breeze-65166b82
  orcid: 0000-0002-3962-270X

# automatic citations
auto-cite:
  plugins:
    - name: sources
      input:
        - ../_data/sources.yaml
  output: ../_data/citations.yaml

### advanced settings

# default front matter parameters for markdown files
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

# collections
collections:
  members:
    output: true

# sass settings
sass:
  sass_dir: css

# syntax highlighting
highlighter: rouge

# plugins
plugins:
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-sitemap
  # - jekyll-github-metadata
  # - jekyll-avatar
  # - jekyll-gist
  # - jekyll-mentions
  # - jekyll-relative-links
  # - jemoji

# jekyll theme
theme: null
