# List your research papers here. The "build research" Python script takes this
# file and uses Manubot to generate a fully-cited "output research" file, which
# is then read by the research list component.

# NOTES:

# Using the research list component, papers will be displayed in order of and
# grouped by date, regardless of how they are listed here.

# Any property that Manubot returns can be manually overridden by putting it
# here, such as "date", "publisher", etc. Use the output file as a reference
# for the expected format (eg dates should be YYYY-MM-DD).

# If a paper is already in the output file (matched by id), that existing
# citation data will be used instead of calling Manubot again. To clear this
# "cache", remove that output entry, or simply delete the whole output file.

# PARAMETERS:

# id:
# An identifier string that Manubot can understand and cite. Also used to
# determine if a paper already exists in the output.

# image:
# Url to a striking image. Use a figure from your paper, or if there are none,
# use a journal logo or issue cover.

# tags:
# A list of key topics/themes of your paper. Aim for 2 to 5. look at other
# papers and try to use similar tags.

# repo:
# A GitHub repo to automatically fetch tags (aka "topics") from.

# extra-links:
# A list of additional links - beyond the main paper link that Manubot returns
# - that will show under your paper citation.

# type:
# Determines link icon and default text. Look in "/_includes/paper-links.html"
# to see what unique types can be specified.

# text:
# Text to show next to icon. If not specified, defaults to some text that
# matches type (see "type")

# link:
# Url to link to. If not specified, defaults to the url that Manubot returns for
# the citation.

# Coupling microwave photons to topological spin textures in Cu2OSeO3. Physical Review B, 104 (10), L100402.
- id: doi:10.1103/physrevb.104.l100402
  image: https://journals.aps.org/prb/article/10.1103/PhysRevB.104.L100402/figures/1/medium

- id: doi:10.1103/PhysRevB.99.140401
  image: https://journals.aps.org/prb/article/10.1103/PhysRevB.99.140401/figures/1/medium

- id: doi:10.1109/CLEOE-EQEC.2019.8873413
  image: https://ieeexplore.ieee.org/mediastore_new/IEEE/content/media/8850908/8871430/8873413/sathi1-p1-sathi-small.gif

- id: doi:10.1038/srep41836

- id: doi:10.1364/OE.25.013714
- id: doi:10.1021/acs.jpcc.6b00150

- id: doi:10.1007/978-3-319-44547-2
- id: doi:10.1557/mre.2014.6
- id: doi:10.1364/OE.20.004419

- id: doi:10.1063/1.3639271
- id: doi:10.1109/AEMC.2011.6256863
- id: doi:10.1109/TUFFC.2010.1685
- id: doi:10.1364/OL.35.000076
- id: doi:10.1016/j.jeurceramsoc.2009.04.027

- id: doi:10.1111/j.1551-2916.2009.02932.x
- id: doi:10.1109/ISAF.2009.5307570
- id: doi:10.1063/1.3086877
- id: doi:10.1063/1.2798055
- id: doi:10.1049/ic:20060293
- id: doi:10.1109/MIKON.2006.4345377
- id: doi:10.1109/TMTT.2006.883655
- id: doi:10.1002/qua.20789
- id: doi:10.1111/j.1551-2916.2005.00458.x
- id: doi:10.1063/1.1605810
- id: doi:10.1063/1.1755426
- id: doi:10.4028/www.scientific.net/KEM.224-226.17
- id: doi:10.4028/www.scientific.net/KEM.224-226.1
- id: doi:10.1049/el:20020579
- id: doi:10.1111/j.1151-2916.2002.tb00348.x
- id: doi:10.1063/1.1532553
- id: doi:10.1016/S0955-2219(01)00324-7
- id: doi:10.1080/01418610108214318
- id: doi:10.1049/el:20000678
- id: doi:10.1049/ip-smt:20000699

- id: https://doi.org/10.1038/nature25970
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1038%2Fnature25970/MediaObjects/41586_2018_Article_BFnature25970_Fig2_HTML.jpg
  link: https://www.nature.com/articles/nature25970
  extra-links:
    - type: preprint
      link: https://arxiv.org/abs/1710.07726

- id: doi:10.1038/s41534-017-0041-3
- id: doi:10.1038/ncomms7215
- id: doi:10.1038/nature11339
